# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UserList = QtWidgets.QListWidget(self.centralwidget)
        self.UserList.setGeometry(QtCore.QRect(0, 0, 300, 600))
        self.UserList.setObjectName("UserList")
        self.Chatbox = QtWidgets.QTextEdit(self.centralwidget)
        self.Chatbox.setGeometry(QtCore.QRect(980, 0, 300, 675))
        self.Chatbox.setReadOnly(True)
        self.Chatbox.setObjectName("Chatbox")
        self.startbt = QtWidgets.QPushButton(self.centralwidget)
        self.startbt.setGeometry(QtCore.QRect(330, 20, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.startbt.setFont(font)
        self.startbt.setObjectName("startbt")
        self.stopbt = QtWidgets.QPushButton(self.centralwidget)
        self.stopbt.setGeometry(QtCore.QRect(650, 20, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.stopbt.setFont(font)
        self.stopbt.setObjectName("stopbt")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(320, 150, 640, 400))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.addbt = QtWidgets.QPushButton(self.centralwidget)
        self.addbt.setGeometry(QtCore.QRect(340, 615, 600, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.addbt.setFont(font)
        self.addbt.setObjectName("addbt")
        self.votebt = QtWidgets.QPushButton(self.centralwidget)
        self.votebt.setGeometry(QtCore.QRect(20, 615, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        self.votebt.setFont(font)
        self.votebt.setObjectName("votebt")
        self.addVotelist = QtWidgets.QTextEdit(self.centralwidget)
        self.addVotelist.setGeometry(QtCore.QRect(320, 560, 640, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.addVotelist.setFont(font)
        self.addVotelist.setObjectName("addVotelist")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chzzk Vote from Seoyyung"))
        self.startbt.setText(_translate("MainWindow", "시  작"))
        self.stopbt.setText(_translate("MainWindow", "마  감"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.addbt.setText(_translate("MainWindow", "항   목   추   가"))
        self.votebt.setText(_translate("MainWindow", "추    첨"))
        self.addVotelist.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'맑은 고딕\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
